// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwRP1_Lt6_LLZqiuRgJ72ge93EJ40n3I8',
    appId: '1:14907450847:web:3b173540d765d23f6c506a',
    messagingSenderId: '14907450847',
    projectId: 'quiz-app-a4df5',
    authDomain: 'quiz-app-a4df5.firebaseapp.com',
    storageBucket: 'quiz-app-a4df5.appspot.com',
    measurementId: 'G-DM7Y2CDC9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYAF0WC1H2hU1DdaJHVg0PdrUnny_rP7k',
    appId: '1:14907450847:android:0b21478c60ac601e6c506a',
    messagingSenderId: '14907450847',
    projectId: 'quiz-app-a4df5',
    storageBucket: 'quiz-app-a4df5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEope29w4-BbdaGGf2n_vKsQQ8vAUrF5Q',
    appId: '1:14907450847:ios:9d2e8bc95059151b6c506a',
    messagingSenderId: '14907450847',
    projectId: 'quiz-app-a4df5',
    storageBucket: 'quiz-app-a4df5.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEope29w4-BbdaGGf2n_vKsQQ8vAUrF5Q',
    appId: '1:14907450847:ios:173a2f6065a9fbaf6c506a',
    messagingSenderId: '14907450847',
    projectId: 'quiz-app-a4df5',
    storageBucket: 'quiz-app-a4df5.appspot.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
